/* eslint-disable key-spacing */
/* eslint-disable sort-keys */
const C = require('./codes')

module.exports = {
  reset:           [C.M_RESET, C.M_RESET],
  bold:            [C.M_OPEN_BOLD, C.M_CLOSE_BOLD_DIM],
  dim:             [C.M_OPEN_DIM, C.M_CLOSE_BOLD_DIM],
  italic:          [C.M_OPEN_ITALIC, C.M_CLOSE_ITALIC],
  underline:       [C.M_OPEN_UNDERLINE, C.M_CLOSE_UNDERLINE],
  inverse:         [C.M_OPEN_INVERSE, C.M_CLOSE_INVERSE],
  hidden:          [C.M_OPEN_HIDDEN, C.M_CLOSE_HIDDEN],
  strikethrough:   [C.M_OPEN_STRIKETHROUGH, C.M_CLOSE_STRIKETHROUGH],
  black:           [C.F_OPEN_BLACK, C.F_CLOSE],
  red:             [C.F_OPEN_RED, C.F_CLOSE],
  green:           [C.F_OPEN_GREEN, C.F_CLOSE],
  yellow:          [C.F_OPEN_YELLOW, C.F_CLOSE],
  blue:            [C.F_OPEN_BLUE, C.F_CLOSE],
  magenta:         [C.F_OPEN_MAGENTA, C.F_CLOSE],
  cyan:            [C.F_OPEN_CYAN, C.F_CLOSE],
  white:           [C.F_OPEN_WHITE, C.F_CLOSE],
  bgBlack:         [C.B_OPEN_BLACK, C.B_CLOSE],
  bgRed:           [C.B_OPEN_RED, C.B_CLOSE],
  bgGreen:         [C.B_OPEN_GREEN, C.B_CLOSE],
  bgYellow:        [C.B_OPEN_YELLOW, C.B_CLOSE],
  bgBlue:          [C.B_OPEN_BLUE, C.B_CLOSE],
  bgMagenta:       [C.B_OPEN_MAGENTA, C.B_CLOSE],
  bgCyan:          [C.B_OPEN_CYAN, C.B_CLOSE],
  bgWhite:         [C.B_OPEN_WHITE, C.B_CLOSE],
  blackBright:     [C.F_OPEN_BLACK_BRIGHT, C.F_CLOSE],
  redBright:       [C.F_OPEN_RED_BRIGHT, C.F_CLOSE],
  greenBright:     [C.F_OPEN_GREEN_BRIGHT, C.F_CLOSE],
  yellowBright:    [C.F_OPEN_YELLOW_BRIGHT, C.F_CLOSE],
  blueBright:      [C.F_OPEN_BLUE_BRIGHT, C.F_CLOSE],
  magentaBright:   [C.F_OPEN_MAGENTA_BRIGHT, C.F_CLOSE],
  cyanBright:      [C.F_OPEN_CYAN_BRIGHT, C.F_CLOSE],
  whiteBright:     [C.F_OPEN_WHITE_BRIGHT, C.F_CLOSE],
  bgBlackBright:   [C.B_OPEN_BLACK_BRIGHT, C.B_CLOSE],
  bgRedBright:     [C.B_OPEN_RED_BRIGHT, C.B_CLOSE],
  bgGreenBright:   [C.B_OPEN_GREEN_BRIGHT, C.B_CLOSE],
  bgYellowBright:  [C.B_OPEN_YELLOW_BRIGHT, C.B_CLOSE],
  bgBlueBright:    [C.B_OPEN_BLUE_BRIGHT, C.B_CLOSE],
  bgMagentaBright: [C.B_OPEN_MAGENTA_BRIGHT, C.B_CLOSE],
  bgCyanBright:    [C.B_OPEN_CYAN_BRIGHT, C.B_CLOSE],
  bgWhiteBright:   [C.B_OPEN_WHITE_BRIGHT, C.B_CLOSE]
}
